### PR TITLE
Feature/dockerize

### PR DESCRIPTION
**Pull request by marcoooo**

### CODE REVIEW

**Comment by marcoooo** [comment]
> What's wrong with Python 3.7?

Travis failed to download the version. Causing the build to fail.

**Comment by thomasmaurel** [comment]
> > What's wrong with Python 3.7?
> 
> Travis failed to download the version. Causing the build to fail.

I know about this one, I already fixed it here: https://github.com/Ensembl/ensembl_production_api/pull/8

**Comment by marcoooo** [comment]
Please can you give a try to QuickStart guide before validating? (Fresh checkout and test)

**Comment by thomasmaurel** [comment]
> Please can you give a try to QuickStart guide before validating? (Fresh checkout and test)

Sure, will do this today

**Pull request merged**
